'use client';

import { Building2, CircleDollarSign, LoaderCircle, Save, TriangleAlert } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { API_URL } from './api-config';
import { getClerkToken } from './clerk-auth';
import type { InspectionProject } from './pipeline-run';
import { budgetPayload, money, type BudgetPeriod, type ClientRecord } from './portfolio-types';

type Scope = { kind: 'client' | 'project'; id: string; orgId: string; name: string; budget?: ClientRecord['budget'] };
export function PortfolioBudgets() {
  const [clients, setClients] = useState<ClientRecord[]>([]); const [projects, setProjects] = useState<InspectionProject[]>([]);
  const [orgId, setOrgId] = useState(''); const [scope, setScope] = useState<Scope | null>(null);
  const [amount, setAmount] = useState(''); const [period, setPeriod] = useState<BudgetPeriod>('monthly');
  const [spend, setSpend] = useState(0); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  async function call(path: string, options: RequestInit = {}) { const token = await getClerkToken(true); if (!token) throw new Error('Administrator sign-in required.'); const r = await fetch(`${API_URL}${path}`, { ...options, headers: { Authorization: `Bearer ${token}`, ...(options.body ? { 'Content-Type': 'application/json' } : {}) } }); const p = await r.json().catch(() => ({})); if (!r.ok) throw new Error(p.detail || `Request failed (${r.status}).`); return p; }
  useEffect(() => { void call('/v1/admin/clients').then((p) => setClients(p.clients || [])).catch((e) => setError(e.message)).finally(() => setLoading(false)); }, []);
  useEffect(() => { if (!orgId) { setProjects([]); return; } void call(`/v1/admin/clients/${encodeURIComponent(orgId)}/projects`).then((p) => setProjects(p.projects || [])).catch((e) => setError(e.message)); }, [orgId]);
  async function choose(next: Scope) { setScope(next); setAmount(next.budget ? String(next.budget.amount) : ''); setPeriod(next.budget?.period || 'monthly'); try { const p = await call(`/v1/admin/usage?scope=${encodeURIComponent(next.id)}&months=1`); setSpend(Number(p.months?.[0]?.est_cost_usd || 0)); } catch { setSpend(0); } }
  async function save() { if (!scope || amount === '') return; setSaving(true); setError(null); try { const path = scope.kind === 'client' ? `/v1/admin/clients/${encodeURIComponent(scope.orgId)}` : `/v1/admin/clients/${encodeURIComponent(scope.orgId)}/projects/${encodeURIComponent(scope.id)}`; const updated = await call(path, { method: 'PATCH', body: JSON.stringify({ budget: budgetPayload(amount, period) }) }); const next = { ...scope, budget: updated.budget }; setScope(next); if (scope.kind === 'client') setClients((all) => all.map((c) => c.org_id === scope.id ? updated : c)); else setProjects((all) => all.map((p) => p.project_id === scope.id ? updated : p)); } catch (e) { setError(e instanceof Error ? e.message : 'Could not save budget.'); } finally { setSaving(false); } }
  const equivalents = useMemo(() => calculate(Number(amount || 0), period), [amount, period]); const periodBudget = equivalents.monthly; const used = periodBudget ? Math.min(100, spend / periodBudget * 100) : 0;
  return <div className="admin-page budget-page"><header className="admin-heading"><div><p className="kicker">CLIENT PORTFOLIOS</p><h1>Budgets & Usage</h1><p>Set notify-only client and project budgets. One entered value automatically calculates every period.</p></div></header>{error && <div className="history-state error"><TriangleAlert size={20} />{error}</div>}{loading ? <div className="history-state"><LoaderCircle className="spinner" /> Loading budgets…</div> : <div className="budget-layout"><aside className="budget-scopes"><h2>Clients</h2>{clients.map((client) => <div key={client.org_id}><button className={scope?.id === client.org_id ? 'active' : ''} onClick={() => { setOrgId(client.org_id); void choose({ kind: 'client', id: client.org_id, orgId: client.org_id, name: client.name, budget: client.budget }); }}><Building2 size={16} /><span><strong>{client.name}</strong><small>{client.budget ? `${money(client.budget.amount)} / ${client.budget.period}` : 'No budget'}</small></span></button>{orgId === client.org_id && projects.map((project) => <button className={`project-scope ${scope?.id === project.project_id ? 'active' : ''}`} key={project.project_id} onClick={() => void choose({ kind: 'project', id: project.project_id, orgId: client.org_id, name: project.name, budget: project.budget })}><span><strong>{project.name}</strong><small>{project.budget ? `${money(project.budget.amount)} / ${project.budget.period}` : 'Inherits client policy'}</small></span></button>)}</div>)}</aside><section className="budget-editor">{scope ? <><div className="budget-editor-heading"><CircleDollarSign size={22} /><div><span>{scope.kind.toUpperCase()} BUDGET</span><h2>{scope.name}</h2></div></div><div className="budget-entry"><label><span>Amount</span><input type="number" min="0" step="0.01" value={amount} onChange={(e) => setAmount(e.target.value)} /></label><label><span>Period</span><select value={period} onChange={(e) => setPeriod(e.target.value as BudgetPeriod)}><option value="hourly">Hourly</option><option value="daily">Daily</option><option value="monthly">Monthly</option><option value="yearly">Yearly</option></select></label></div><div className="budget-equivalents">{Object.entries(equivalents).map(([key, value]) => <div key={key}><span>{key}</span><strong>{money(value)}</strong></div>)}</div><div className="budget-progress"><div><span>Current month usage</span><strong>{money(spend)} of {money(periodBudget)}</strong></div><progress max="100" value={used} /><small>{used.toFixed(1)}% used · notifications at 50%, 75%, 90%, and 100%</small></div><button className="primary-button" disabled={saving || amount === ''} onClick={() => void save()}>{saving ? <LoaderCircle className="spinner" size={16} /> : <Save size={16} />} Save budget</button></> : <div className="history-state"><CircleDollarSign size={30} /><strong>Select a client or project</strong><span>Its budget and current usage will appear here.</span></div>}</section></div>}</div>;
}
function calculate(amount: number, period: BudgetPeriod) { const annual = period === 'hourly' ? amount * 8766 : period === 'daily' ? amount * 365.25 : period === 'monthly' ? amount * 12 : amount; return { hourly: annual / 8766, daily: annual / 365.25, monthly: annual / 12, yearly: annual }; }
